// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHc8NxyNS-WINFvPH4q_XKgOxZKAR1g_0',
    appId: '1:546618041879:web:fa2b2ef2d976fd864e1e52',
    messagingSenderId: '546618041879',
    projectId: 'lifeline-42717',
    authDomain: 'lifeline-42717.firebaseapp.com',
    storageBucket: 'lifeline-42717.firebasestorage.app',
    measurementId: 'G-YKYTYWYWZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02I1g4ZREeC1H6H2BMVNE1a7KRvcKQXc',
    appId: '1:546618041879:android:7139ae57dd940f674e1e52',
    messagingSenderId: '546618041879',
    projectId: 'lifeline-42717',
    storageBucket: 'lifeline-42717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbyCPhGGRvipdwAqcUTyT0LCnKVWdkZLE',
    appId: '1:546618041879:ios:c50405e541a19e874e1e52',
    messagingSenderId: '546618041879',
    projectId: 'lifeline-42717',
    storageBucket: 'lifeline-42717.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbyCPhGGRvipdwAqcUTyT0LCnKVWdkZLE',
    appId: '1:546618041879:ios:c50405e541a19e874e1e52',
    messagingSenderId: '546618041879',
    projectId: 'lifeline-42717',
    storageBucket: 'lifeline-42717.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHc8NxyNS-WINFvPH4q_XKgOxZKAR1g_0',
    appId: '1:546618041879:web:2e6f3f5aab4bf0b24e1e52',
    messagingSenderId: '546618041879',
    projectId: 'lifeline-42717',
    authDomain: 'lifeline-42717.firebaseapp.com',
    storageBucket: 'lifeline-42717.firebasestorage.app',
    measurementId: 'G-NX22HF0BVZ',
  );
}
